In [1]:
import pandas as pd
import plotly.express as px
#import hvplot.pandas
from sklearn.cluster import KMeans

In [2]:
# Loading data
file_path = "../sources/datafiniti-restaurants-burritos-and-tacos/data/just_tacos_and_burritos.csv"
all_tacos = pd.read_csv(file_path)
all_tacos.head(10)

id                   address  \
0  AVwc__cikufWRAb51QjV         610 Commercial St   
1  AVwc__cikufWRAb51QjV         610 Commercial St   
2  AVwc__dF_7pvs4fz1Ncy      9521 Morton Davis Dr   
3  AVwc__kCByjofQCxkdm-  10550 W I 25 Frontage Rd   
4  AVwc__WtByjofQCxkdkR             8495 W 3rd St   
5  AVwc__WtByjofQCxkdkR             8495 W 3rd St   
6  AVwc__WtByjofQCxkdkR             8495 W 3rd St   
7  AVwc__WtByjofQCxkdkR             8495 W 3rd St   
8  AVwc__WtByjofQCxkdkR             8495 W 3rd St   
9  AVwc__WtByjofQCxkdkR             8495 W 3rd St   

                                          categories         city country  \
0  Restaurant Delivery Service,Restaurants,Pizza,...     Atchison      US   
1  Restaurant Delivery Service,Restaurants,Pizza,...     Atchison      US   
2       Golf Course, American Restaurant, and Resort    Patterson      US   
3                               Fast Food Restaurant     Longmont      US   
4  Mexican Restaurant Mid-City West,Mexican Resta...  Los Angeles      US   
5  Mexican Restaurant Mid-City West,Mexican Resta...  Los Angeles      US   
6  Mexican Restaurant Mid-City West,Mexican Resta...  Los Angeles      US   
7  Mexican Restaurant Mid-City West,Mexican Resta...  Los Angeles      US   
8  Mexican Restaurant Mid-City West,Mexican Resta...  Los Angeles      US   
9  Mexican Restaurant Mid-City West,Mexican Resta...  Los Angeles      US   

                      cuisines             dateadded           dateupdated  \
0  Restaurant Delivery Service  2016-03-02T11:49:34Z  2017-02-01T18:04:44Z   
1  Restaurant Delivery Service  2016-03-02T11:49:34Z  2017-02-01T18:04:44Z   
2                          NaN  2016-10-14T01:58:25Z  2016-10-14T01:58:25Z   
3                          NaN  2016-09-09T17:30:34Z  2016-10-04T05:15:17Z   
4                      Mexican  2016-05-19T11:50:25Z  2016-09-11T00:06:37Z   
5                      Mexican  2016-05-19T11:50:25Z  2016-09-11T00:06:37Z   
6                      Mexican  2016-05-19T11:50:25Z  2016-09-11T00:06:37Z   
7                      Mexican  2016-05-19T11:50:25Z  2016-09-11T00:06:37Z   
8                      Mexican  2016-05-19T11:50:25Z  2016-09-11T00:06:37Z   
9                      Mexican  2016-05-19T11:50:25Z  2016-09-11T00:06:37Z   

                                                keys   latitude  ...  \
0          us/ks/atchison/610commercialst/-138126000  39.561570  ...   
1          us/ks/atchison/610commercialst/-138126000  39.561570  ...   
2  us/grayson/patterson/9521mortondavisdr/-522005016  37.401855  ...   
3  us/niwot/longmont/10550wi25frontagerd/-1161002137        NaN  ...   
4   us/bicentennial/losangeles/8495w3rdst/-251199537  34.080724  ...   
5   us/bicentennial/losangeles/8495w3rdst/-251199537  34.080724  ...   
6   us/bicentennial/losangeles/8495w3rdst/-251199537  34.080724  ...   
7   us/bicentennial/losangeles/8495w3rdst/-251199537  34.080724  ...   
8   us/bicentennial/losangeles/8495w3rdst/-251199537  34.080724  ...   
9   us/bicentennial/losangeles/8495w3rdst/-251199537  34.080724  ...   

                                   menus_description  \
0                                                NaN   
1  Beef, onion, cheddar cheese, lettuce,  refried...   
2  Beef barbacoa or chicken, spanish rice, pico d...   
3                                                NaN   
4  Wahoo, avocado, cabbage, pico de gallo  and av...   
5  Hand breaded fried wahoo, topped with   cabbag...   
6  Any combination of two original baja or americ...   
7  Grilled corn tortillas with salsa, onions and ...   
8                                                NaN   
9                        Cabo style or caesar style.   

                      menus_name                               name  \
0                           Taco                    Gambino's Pizza   
1                           Taco                    Gambino's Pizza   
2               Smotherd Burrito  Diablo Grande Golf & Country Club   
3                Sausage Burrito    

In [3]:
all_tacos.columns.tolist()

['id',
 'address',
 'categories',
 'city',
 'country',
 'cuisines',
 'dateadded',
 'dateupdated',
 'keys',
 'latitude',
 'longitude',
 'menupageurl',
 'menus_amountmax',
 'menus_amountmin',
 'menus_category',
 'menus_currency',
 'menus_dateseen',
 'menus_description',
 'menus_name',
 'name',
 'postalcode',
 'pricerangecurrency',
 'pricerangemin',
 'pricerangemax',
 'province',
 'websites',
 'location']

In [4]:
all_tacos = all_tacos.drop(['id', 'address', 'categories','city', 'country','dateadded','dateupdated','keys', 'menupageurl','menus_amountmax',
 'menus_amountmin','menus_currency','menus_dateseen', 'menus_name','postalcode','pricerangecurrency','pricerangemin','pricerangemax','province','websites',], axis=1)
all_tacos.head()

cuisines   latitude   longitude menus_category  \
0  Restaurant Delivery Service  39.561570  -95.121020            NaN   
1  Restaurant Delivery Service  39.561570  -95.121020            NaN   
2                          NaN  37.401855 -121.266703            NaN   
3                          NaN        NaN         NaN            NaN   
4                      Mexican  34.080724 -118.389578            NaN   

                                   menus_description  \
0                                                NaN   
1  Beef, onion, cheddar cheese, lettuce,  refried...   
2  Beef barbacoa or chicken, spanish rice, pico d...   
3                                                NaN   
4  Wahoo, avocado, cabbage, pico de gallo  and av...   

                                name                        location  
0                    Gambino's Pizza       POINT(-95.12102 39.56157)  
1                    Gambino's Pizza       POINT(-95.12102 39.56157)  
2  Diablo Grande Golf & Country Club    POINT(-121.266703 37.401855)  
3                         Mcdonald's                             NaN  
4           Baja Fresh Mexican Grill  POINT(-118.3895776 34.0807243)

In [5]:
all_tacos = all_tacos.drop(['menus_category', 'menus_description','location','cuisines'], axis=1)
all_tacos.head(10)

latitude   longitude                               name
0  39.561570  -95.121020                    Gambino's Pizza
1  39.561570  -95.121020                    Gambino's Pizza
2  37.401855 -121.266703  Diablo Grande Golf & Country Club
3        NaN         NaN                         Mcdonald's
4  34.080724 -118.389578           Baja Fresh Mexican Grill
5  34.080724 -118.389578           Baja Fresh Mexican Grill
6  34.080724 -118.389578           Baja Fresh Mexican Grill
7  34.080724 -118.389578           Baja Fresh Mexican Grill
8  34.080724 -118.389578           Baja Fresh Mexican Grill
9  34.080724 -118.389578           Baja Fresh Mexican Grill

In [6]:
all_tacos['is_tacos'] = 'tacos'
all_tacos.head(10)

latitude   longitude                               name is_tacos
0  39.561570  -95.121020                    Gambino's Pizza    tacos
1  39.561570  -95.121020                    Gambino's Pizza    tacos
2  37.401855 -121.266703  Diablo Grande Golf & Country Club    tacos
3        NaN         NaN                         Mcdonald's    tacos
4  34.080724 -118.389578           Baja Fresh Mexican Grill    tacos
5  34.080724 -118.389578           Baja Fresh Mexican Grill    tacos
6  34.080724 -118.389578           Baja Fresh Mexican Grill    tacos
7  34.080724 -118.389578           Baja Fresh Mexican Grill    tacos
8  34.080724 -118.389578           Baja Fresh Mexican Grill    tacos
9  34.080724 -118.389578           Baja Fresh Mexican Grill    tacos

In [8]:
all_tacos.shape[0]

77260

In [9]:
all_tacos = all_tacos.dropna(axis=0)
all_tacos.shape[0]

55633

In [13]:
all_tacos = all_tacos.drop(['name'], axis=1)
all_tacos.head(10)

latitude   longitude is_tacos
0   39.561570  -95.121020    tacos
1   39.561570  -95.121020    tacos
2   37.401855 -121.266703    tacos
4   34.080724 -118.389578    tacos
5   34.080724 -118.389578    tacos
6   34.080724 -118.389578    tacos
7   34.080724 -118.389578    tacos
8   34.080724 -118.389578    tacos
9   34.080724 -118.389578    tacos
10  34.080724 -118.389578    tacos

In [10]:
# Loading data
file_path = "../sources/bigfoot_sightings.csv"
all_bigfoot = pd.read_csv(file_path)
all_bigfoot.head(10)

Unnamed: 0  number classification                  timestamp  latitude  \
0           0     637        Class A  2000-06-16 12:00:00+00:00  61.50000   
1           1    2917        Class A  1995-05-15 12:00:00+00:00  55.18720   
2           2    7963        Class A  2004-02-09 12:00:00+00:00  55.20350   
3           3    9317        Class A  2004-06-18 12:00:00+00:00  62.93750   
4           4   13038        Class A  2004-02-15 12:00:00+00:00  61.05950   
5           5   23666        Class A  2008-04-23 12:00:00+00:00  62.77335   
6           6   26604        Class A  2009-07-15 12:00:00+00:00  64.89139   
7           7     179        Class A  1981-09-15 12:00:00+00:00  32.31435   
8           8     245        Class A  1999-07-15 12:00:00+00:00  33.28375   
9           9     416        Class A  1983-11-15 12:00:00+00:00  34.95605   

   longitude                                             report  \
0 -142.90000   Campers' encounter just after dark in the Wra...   
1 -132.79820               Family observes large biped from car   
2 -132.82020      Sasquatch walks past window of house at night   
3 -141.56670   Driver on Alcan Highway has noon, road encoun...   
4 -149.78530   Snowmobiler has encounter in deep snow near P...   
5 -141.31650   Passenger on the Alcan Highway sees a tall bi...   
6 -147.81420   Daytime sighting of reddish-colored bigfoot n...   
7  -85.16235   Man and witnesses have two seperate sighting,...   
8  -87.32655   Two outdoorsman fishing, loud vocalizations, ...   
9  -86.45590   A resident's early evening sighting next to h...   

                                           key_words  
0  Campers' encounter dark Wrangell - St. Elias N...  
1                    Family observes large biped car  
2            Sasquatch walks past window house night  
3  Driver Alcan Highway noon, road encounter near...  
4    Snowmobiler encounter deep snow near Potter, AK  
5  Passenger Alcan Highway sees tall bipedal crea...  
6  Daytime sighting reddish-colored bigfoot near ...  
7  Man witnesses two seperate sighting, 1st fishi...  
8  Two outdoorsman fishing, loud vocalizations, f...  
9  A resident's early evening sighting next home ...

In [11]:
all_bigfoot = all_bigfoot.drop(['Unnamed: 0', 'number','timestamp','report','key_words'], axis=1)
all_bigfoot.head()

classification  latitude  longitude
0        Class A   61.5000  -142.9000
1        Class A   55.1872  -132.7982
2        Class A   55.2035  -132.8202
3        Class A   62.9375  -141.5667
4        Class A   61.0595  -149.7853

In [12]:
all_bigfoot['is_bigfoot'] = 'bigfoot'
all_bigfoot.head(10)

classification  latitude  longitude is_bigfoot
0        Class A  61.50000 -142.90000    bigfoot
1        Class A  55.18720 -132.79820    bigfoot
2        Class A  55.20350 -132.82020    bigfoot
3        Class A  62.93750 -141.56670    bigfoot
4        Class A  61.05950 -149.78530    bigfoot
5        Class A  62.77335 -141.31650    bigfoot
6        Class A  64.89139 -147.81420    bigfoot
7        Class A  32.31435  -85.16235    bigfoot
8        Class A  33.28375  -87.32655    bigfoot
9        Class A  34.95605  -86.45590    bigfoot

In [14]:
all_bigfoot = all_bigfoot.drop(['classification'], axis=1)
all_bigfoot.head()

latitude  longitude is_bigfoot
0   61.5000  -142.9000    bigfoot
1   55.1872  -132.7982    bigfoot
2   55.2035  -132.8202    bigfoot
3   62.9375  -141.5667    bigfoot
4   61.0595  -149.7853    bigfoot

In [15]:
everything_tacos = pd.concat([all_bigfoot, all_tacos], ignore_index=True, sort=False)
everything_tacos.head(10)

latitude  longitude is_bigfoot is_tacos
0  61.50000 -142.90000    bigfoot      NaN
1  55.18720 -132.79820    bigfoot      NaN
2  55.20350 -132.82020    bigfoot      NaN
3  62.93750 -141.56670    bigfoot      NaN
4  61.05950 -149.78530    bigfoot      NaN
5  62.77335 -141.31650    bigfoot      NaN
6  64.89139 -147.81420    bigfoot      NaN
7  32.31435  -85.16235    bigfoot      NaN
8  33.28375  -87.32655    bigfoot      NaN
9  34.95605  -86.45590    bigfoot      NaN

In [16]:
def change_string(is_bigfoot):
    if is_bigfoot == "bigfoot":
        return 1
    else:
        return 0
    
everything_tacos["is_bigfoot"] = everything_tacos["is_bigfoot"].apply(change_string)
everything_tacos.head(10)

latitude  longitude  is_bigfoot is_tacos
0  61.50000 -142.90000           1      NaN
1  55.18720 -132.79820           1      NaN
2  55.20350 -132.82020           1      NaN
3  62.93750 -141.56670           1      NaN
4  61.05950 -149.78530           1      NaN
5  62.77335 -141.31650           1      NaN
6  64.89139 -147.81420           1      NaN
7  32.31435  -85.16235           1      NaN
8  33.28375  -87.32655           1      NaN
9  34.95605  -86.45590           1      NaN

In [19]:
def change_string2(is_tacos):
    if is_tacos == "tacos":
        return 1
    else:
        return 0
    
everything_tacos["is_tacos"] = everything_tacos["is_tacos"].apply(change_string2)
everything_tacos.head(10)

latitude  longitude  is_bigfoot  is_tacos
0  61.50000 -142.90000           1         0
1  55.18720 -132.79820           1         0
2  55.20350 -132.82020           1         0
3  62.93750 -141.56670           1         0
4  61.05950 -149.78530           1         0
5  62.77335 -141.31650           1         0
6  64.89139 -147.81420           1         0
7  32.31435  -85.16235           1         0
8  33.28375  -87.32655           1         0
9  34.95605  -86.45590           1         0

In [20]:
#List the data types
everything_tacos.dtypes

latitude      float64
longitude     float64
is_bigfoot      int64
is_tacos        int64
dtype: object

In [61]:
doubles = everything_tacos[everything_tacos[['latitude', 'longitude']].duplicated() == True]
print(doubles)

        latitude  longitude  is_bigfoot  is_tacos
42     33.895700  -87.53395           1         0
147    38.933330 -119.98330           1         0
171    38.933330 -119.98330           1         0
173    40.266390 -123.86920           1         0
178    39.688330 -123.48170           1         0
...          ...        ...         ...       ...
59438  37.751392 -122.43018           0         1
59439  37.751392 -122.43018           0         1
59440  37.751392 -122.43018           0         1
59441  37.751392 -122.43018           0         1
59442  37.751392 -122.43018           0         1

[40972 rows x 4 columns]


In [62]:
everything_tacos.shape[0]

59443

In [64]:
everything_tacos = everything_tacos.drop_duplicates()
everything_tacos.shape[0]

18471

In [65]:
second_doubles = everything_tacos[everything_tacos[['latitude', 'longitude']].duplicated() == True]
print(second_doubles)

Empty DataFrame
Columns: [latitude, longitude, is_bigfoot, is_tacos]
Index: []


In [66]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()

In [67]:
# Generate our categorical variable list
tacos_not_tacos = data_scaler.fit_transform(everything_tacos)

In [68]:
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()


In [69]:
tacos_not_tacos[:5]

array([[ 4.46969703,  0.01414929,  1.97569516, -1.97569516],
       [ 3.28593524,  0.0141602 ,  1.97569516, -1.97569516],
       [ 3.28899178,  0.01416017,  1.97569516, -1.97569516],
       [ 4.73925373,  0.01415073,  1.97569516, -1.97569516],
       [ 4.38709547,  0.01414186,  1.97569516, -1.97569516]])

In [70]:
import numpy as np
print(np.mean(tacos_not_tacos[:,0]))
print(np.std(tacos_not_tacos[:,0]))

-2.615825133002372e-16
1.0


In [71]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [72]:
# Define the features set.
X = everything_tacos.copy()
X = X.drop("is_bigfoot", axis=1)
X.head()


latitude  longitude  is_tacos
0   61.5000  -142.9000         0
1   55.1872  -132.7982         0
2   55.2035  -132.8202         0
3   62.9375  -141.5667         0
4   61.0595  -149.7853         0

In [73]:
# Define the target set.
y = everything_tacos["is_bigfoot"].values
y[:5]


array([1, 1, 1, 1, 1])

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [75]:
# Determine the shape of our training and testing sets.
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(13853, 3)
(4618, 3)
(13853,)
(4618,)


In [76]:
# Splitting into Train and Test sets into an 80/20 split.
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, random_state=78, train_size=0.80)

In [77]:
# Determine the shape of our training and testing sets.
print(X_train2.shape)
print(X_test2.shape)
print(y_train2.shape)
print(y_test2.shape)


(14776, 3)
(3695, 3)
(14776,)
(3695,)


In [78]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [79]:
# Creating the decision tree classifier instance.
model = tree.DecisionTreeClassifier()
# Fitting the model.
model = model.fit(X_train_scaled, y_train)

In [80]:
# Making predictions using the testing data.
predictions = model.predict(X_test_scaled)

In [81]:
predictions

array([0, 1, 0, ..., 0, 0, 1])

In [82]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm

array([[3667,    0],
       [   0,  951]])

In [83]:
# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

Predicted 0  Predicted 1
Actual 0         3667            0
Actual 1            0          951

In [84]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [85]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0         3667            0
Actual 1            0          951

Accuracy Score : 1.0
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3667
           1       1.00      1.00      1.00       951

    accuracy                           1.00      4618
   macro avg       1.00      1.00      1.00      4618
weighted avg       1.00      1.00      1.00      4618



In [86]:
from sklearn.ensemble import RandomForestClassifier


In [87]:
# Define the features set.
X = everything_tacos.copy()
X = X.drop("is_tacos", axis=1)
X.head()

latitude  longitude  is_bigfoot
0   61.5000  -142.9000           1
1   55.1872  -132.7982           1
2   55.2035  -132.8202           1
3   62.9375  -141.5667           1
4   61.0595  -149.7853           1

In [88]:
# Define the target set.
y = everything_tacos["is_tacos"].values
y[:5]

array([0, 0, 0, 0, 0])

In [89]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [90]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [91]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=500, random_state=78) 

In [92]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [93]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [94]:
predictions

array([1, 0, 1, ..., 1, 1, 0])

In [95]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

Predicted 0  Predicted 1
Actual 0          951            0
Actual 1            0         3667

In [96]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [97]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0          951            0
Actual 1            0         3667

Accuracy Score : 1.0
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       951
           1       1.00      1.00      1.00      3667

    accuracy                           1.00      4618
   macro avg       1.00      1.00      1.00      4618
weighted avg       1.00      1.00      1.00      4618



In [98]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances


array([0.06168074, 0.01563528, 0.92268398])

In [99]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.9226839809622381, 'is_bigfoot'),
 (0.06168073625355821, 'latitude'),
 (0.01563528278420355, 'longitude')]

In [58]:
import joblib


In [59]:
# save
joblib.dump(RandomForestClassifier, "./random_forest3.joblib")


['./random_forest3.joblib']

In [60]:
# load, no need to initialize the loaded_rf
loaded_rf = joblib.load("./random_forest3.joblib")