In [1]:
import pandas as pd
import plotly.express as px
#import hvplot.pandas
from sklearn.cluster import KMeans

In [2]:
# Loading data
file_path = "sources/bigfoot_movement.csv"
df_bigfoot = pd.read_csv(file_path)
df_bigfoot.head(10)

Unnamed: 0  number classification                  timestamp  latitude  \
0         202   14338        Class A  1869-11-10 12:00:00+00:00  37.39555   
1        1380   14358        Class A  1921-01-14 12:00:00+00:00  41.01865   
2        2685   24413        Class B  1925-10-14 12:00:00+00:00  31.08774   
3        3306    2477        Class B  1930-09-30 12:00:00+00:00  31.40444   
4        2843   24102        Class B  1932-01-01 12:00:00+00:00  39.80751   
5         257   14328        Class A  1934-03-04 12:00:00+00:00  49.17500   
6         711   14336        Class A  1937-08-16 12:00:00+00:00  38.01000   
7        3302    2395        Class B  1938-06-30 12:00:00+00:00  32.51750   
8        1659    1689        Class A  1941-10-15 12:00:00+00:00  46.24639   
9        3114    1303        Class B  1942-04-01 12:00:00+00:00  34.73153   

      longitude                                             report  \
0 -1.214871e+02   Old newspaper article (Titusville Morning Her...   
1 -7.837700e+01   Old newspaper article (Clearfield Progress - ...   
2 -9.184467e+01   Woman recounts a tale her Grandfather told he...   
3 -9.570861e+01   Nine foot tall brown/black creature seen carr...   
4 -9.486840e+07   Recollections of numerous encounters at a log...   
5 -1.215250e+02   Old newspaper article (Lima, Ohio) about enco...   
6 -8.732030e+01   Old newspaper article (The Hammond Times) men...   
7 -9.680417e+01   Sighting at night by a group of coon hunters;...   
8 -1.208681e+02   A tall black creature covered with hair and v...   
9 -9.981514e+01   Sisters observe tall hairy creature running a...   

                                           key_words  month  year  
0  Old newspaper article (Titusville Morning Hera...     11  1869  
1  Old newspaper article (Clearfield Progress - P...      1  1921  
2  Woman recounts tale Grandfather told frighteni...     10  1925  
3  Nine foot tall brown/black creature seen carry...      9  1930  
4  Recollections numerous encounters logging camp...      1  1932  
5  Old newspaper article (Lima, Ohio) encounters ...      3  1934  
6  Old newspaper article (The Hammond Times) ment...      8  1937  
7  Sighting night group coon hunters; Screams als...      6  1938  
8  A tall black creature covered hair muscular se...     10  1941  
9   Sisters observe tall hairy creature running away      4  1942

In [3]:
df_bigfoot.columns.tolist()

['Unnamed: 0',
 'number',
 'classification',
 'timestamp',
 'latitude',
 'longitude',
 'report',
 'key_words',
 'month',
 'year']

In [4]:
skeleton_df = df_bigfoot.drop(['Unnamed: 0','number', 'timestamp','key_words', 'report'], axis=1)
skeleton_df.head()

classification  latitude     longitude  month  year
0        Class A  37.39555 -1.214871e+02     11  1869
1        Class A  41.01865 -7.837700e+01      1  1921
2        Class B  31.08774 -9.184467e+01     10  1925
3        Class B  31.40444 -9.570861e+01      9  1930
4        Class B  39.80751 -9.486840e+07      1  1932

In [5]:
#List the data types
skeleton_df.dtypes

classification     object
latitude          float64
longitude         float64
month               int64
year                int64
dtype: object

In [6]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
skeleton_df["classification"] = label_encoder.fit_transform(skeleton_df["classification"])
skeleton_df.head()

classification  latitude     longitude  month  year
0               0  37.39555 -1.214871e+02     11  1869
1               0  41.01865 -7.837700e+01      1  1921
2               1  31.08774 -9.184467e+01     10  1925
3               1  31.40444 -9.570861e+01      9  1930
4               1  39.80751 -9.486840e+07      1  1932

In [7]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()

In [8]:
# Generate our categorical variable list
skeleton_scaled = data_scaler.fit_transform(skeleton_df)

In [9]:
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()


In [10]:
skeleton_scaled[:5]

array([[-9.95669352e-01, -3.90159951e-01,  3.12635588e-02,
         1.22560050e+00, -9.09830040e+00],
       [-9.95669352e-01,  2.07161839e-01,  3.12847056e-02,
        -2.00792758e+00, -5.41410491e+00],
       [ 9.65809568e-01, -1.43009602e+00,  3.12780993e-02,
         9.02247691e-01, -5.13070526e+00],
       [ 9.65809568e-01, -1.37788332e+00,  3.12762040e-02,
         5.78894883e-01, -4.77645569e+00],
       [ 9.65809568e-01,  7.48744042e-03, -4.65044433e+01,
        -2.00792758e+00, -4.63475586e+00]])

In [11]:
import numpy as np
print(np.mean(skeleton_scaled[:,0]))
print(np.std(skeleton_scaled[:,0]))

2.983906501879686e-17
1.0


In [12]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [13]:
# Define the features set.
X = skeleton_df.copy()
X = X.drop("classification", axis=1)
X.head()


latitude     longitude  month  year
0  37.39555 -1.214871e+02     11  1869
1  41.01865 -7.837700e+01      1  1921
2  31.08774 -9.184467e+01     10  1925
3  31.40444 -9.570861e+01      9  1930
4  39.80751 -9.486840e+07      1  1932

In [14]:
# Define the target set.
y = skeleton_df["classification"].values
y[:5]


array([0, 0, 1, 1, 1])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [16]:
# Determine the shape of our training and testing sets.
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(2857, 4)
(953, 4)
(2857,)
(953,)


In [17]:
# Splitting into Train and Test sets into an 80/20 split.
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, random_state=78, train_size=0.80)

In [18]:
# Determine the shape of our training and testing sets.
print(X_train2.shape)
print(X_test2.shape)
print(y_train2.shape)
print(y_test2.shape)


(3048, 4)
(762, 4)
(3048,)
(762,)


In [19]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [20]:
# Creating the decision tree classifier instance.
model = tree.DecisionTreeClassifier()
# Fitting the model.
model = model.fit(X_train_scaled, y_train)

In [21]:
# Making predictions using the testing data.
predictions = model.predict(X_test_scaled)

In [22]:
predictions

array([1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 2, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 2, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,

In [23]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm

array([[272, 208,   5],
       [206, 255,   3],
       [  1,   3,   0]])

In [25]:
# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1", "Actual 2"], columns=["Predicted 0", "Predicted 1", "Predicted 2"])

cm_df

Predicted 0  Predicted 1  Predicted 2
Actual 0          272          208            5
Actual 1          206          255            3
Actual 2            1            3            0

In [26]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [27]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1  Predicted 2
Actual 0          272          208            5
Actual 1          206          255            3
Actual 2            1            3            0

Accuracy Score : 0.55299055613851
Classification Report
              precision    recall  f1-score   support

           0       0.57      0.56      0.56       485
           1       0.55      0.55      0.55       464
           2       0.00      0.00      0.00         4

    accuracy                           0.55       953
   macro avg       0.37      0.37      0.37       953
weighted avg       0.56      0.55      0.55       953



In [28]:
from sklearn.ensemble import RandomForestClassifier


In [30]:
# Define the features set.
X = skeleton_df.copy()
X = X.drop("classification", axis=1)
X.head()

latitude     longitude  month  year
0  37.39555 -1.214871e+02     11  1869
1  41.01865 -7.837700e+01      1  1921
2  31.08774 -9.184467e+01     10  1925
3  31.40444 -9.570861e+01      9  1930
4  39.80751 -9.486840e+07      1  1932

In [31]:
# Define the target set.
y = skeleton_df["classification"].values
y[:5]

array([0, 0, 1, 1, 1])

In [32]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [33]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [34]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=500, random_state=78) 

In [35]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [36]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [37]:
predictions

array([0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,

In [38]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1", "Actual 2"], columns=["Predicted 0", "Predicted 1", "Predicted 2"])

cm_df

Predicted 0  Predicted 1  Predicted 2
Actual 0          279          206            0
Actual 1          204          260            0
Actual 2            4            0            0

In [39]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [40]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1  Predicted 2
Actual 0          279          206            0
Actual 1          204          260            0
Actual 2            4            0            0

Accuracy Score : 0.565582371458552
Classification Report
              precision    recall  f1-score   support

           0       0.57      0.58      0.57       485
           1       0.56      0.56      0.56       464
           2       0.00      0.00      0.00         4

    accuracy                           0.57       953
   macro avg       0.38      0.38      0.38       953
weighted avg       0.56      0.57      0.56       953



/opt/anaconda3/envs/c19/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/envs/c19/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/envs/c19/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [41]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances


array([0.36303852, 0.25508536, 0.15403854, 0.22783758])

In [42]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.36303852084823723, 'latitude'),
 (0.255085357321569, 'longitude'),
 (0.22783758365877146, 'year'),
 (0.1540385381714222, 'month')]

In [43]:
import joblib


In [45]:
# save
joblib.dump(RandomForestClassifier, "./random_forest3.joblib")


['./random_forest3.joblib']

In [46]:
# load, no need to initialize the loaded_rf
loaded_rf = joblib.load("./random_forest3.joblib")