In [1]:
import pandas as pd
import plotly.express as px
#import hvplot.pandas
from sklearn.cluster import KMeans

In [2]:
# Loading data
file_path = "sources/bigfoot_movement.csv"
df_bigfoot = pd.read_csv(file_path)
df_bigfoot.head(10)

Unnamed: 0  number classification                  timestamp  latitude  \
0         202   14338        Class A  1869-11-10 12:00:00+00:00  37.39555   
1        1380   14358        Class A  1921-01-14 12:00:00+00:00  41.01865   
2        2685   24413        Class B  1925-10-14 12:00:00+00:00  31.08774   
3        3306    2477        Class B  1930-09-30 12:00:00+00:00  31.40444   
4        2843   24102        Class B  1932-01-01 12:00:00+00:00  39.80751   
5         257   14328        Class A  1934-03-04 12:00:00+00:00  49.17500   
6         711   14336        Class A  1937-08-16 12:00:00+00:00  38.01000   
7        3302    2395        Class B  1938-06-30 12:00:00+00:00  32.51750   
8        1659    1689        Class A  1941-10-15 12:00:00+00:00  46.24639   
9        3114    1303        Class B  1942-04-01 12:00:00+00:00  34.73153   

      longitude                                             report  \
0 -1.214871e+02   Old newspaper article (Titusville Morning Her...   
1 -7.837700e+01   Old newspaper article (Clearfield Progress - ...   
2 -9.184467e+01   Woman recounts a tale her Grandfather told he...   
3 -9.570861e+01   Nine foot tall brown/black creature seen carr...   
4 -9.486840e+07   Recollections of numerous encounters at a log...   
5 -1.215250e+02   Old newspaper article (Lima, Ohio) about enco...   
6 -8.732030e+01   Old newspaper article (The Hammond Times) men...   
7 -9.680417e+01   Sighting at night by a group of coon hunters;...   
8 -1.208681e+02   A tall black creature covered with hair and v...   
9 -9.981514e+01   Sisters observe tall hairy creature running a...   

                                           key_words  month  year  
0  Old newspaper article (Titusville Morning Hera...     11  1869  
1  Old newspaper article (Clearfield Progress - P...      1  1921  
2  Woman recounts tale Grandfather told frighteni...     10  1925  
3  Nine foot tall brown/black creature seen carry...      9  1930  
4  Recollections numerous encounters logging camp...      1  1932  
5  Old newspaper article (Lima, Ohio) encounters ...      3  1934  
6  Old newspaper article (The Hammond Times) ment...      8  1937  
7  Sighting night group coon hunters; Screams als...      6  1938  
8  A tall black creature covered hair muscular se...     10  1941  
9   Sisters observe tall hairy creature running away      4  1942

In [3]:
df_bigfoot.columns.tolist()

['Unnamed: 0',
 'number',
 'classification',
 'timestamp',
 'latitude',
 'longitude',
 'report',
 'key_words',
 'month',
 'year']

In [4]:
skeleton_df = df_bigfoot.drop(['Unnamed: 0','number', 'timestamp','key_words', 'report'], axis=1)
skeleton_df.head()

classification  latitude     longitude  month  year
0        Class A  37.39555 -1.214871e+02     11  1869
1        Class A  41.01865 -7.837700e+01      1  1921
2        Class B  31.08774 -9.184467e+01     10  1925
3        Class B  31.40444 -9.570861e+01      9  1930
4        Class B  39.80751 -9.486840e+07      1  1932

In [5]:
#List the data types
skeleton_df.dtypes

classification     object
latitude          float64
longitude         float64
month               int64
year                int64
dtype: object

In [6]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
skeleton_df["classification"] = label_encoder.fit_transform(skeleton_df["classification"])
skeleton_df.head()

classification  latitude     longitude  month  year
0               0  37.39555 -1.214871e+02     11  1869
1               0  41.01865 -7.837700e+01      1  1921
2               1  31.08774 -9.184467e+01     10  1925
3               1  31.40444 -9.570861e+01      9  1930
4               1  39.80751 -9.486840e+07      1  1932

In [7]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()

In [8]:
# Generate our categorical variable list
skeleton_scaled = data_scaler.fit_transform(skeleton_df)

In [9]:
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()


In [10]:
skeleton_scaled[:5]

array([[-9.95669352e-01, -3.90159951e-01,  3.12635588e-02,
         1.22560050e+00, -9.09830040e+00],
       [-9.95669352e-01,  2.07161839e-01,  3.12847056e-02,
        -2.00792758e+00, -5.41410491e+00],
       [ 9.65809568e-01, -1.43009602e+00,  3.12780993e-02,
         9.02247691e-01, -5.13070526e+00],
       [ 9.65809568e-01, -1.37788332e+00,  3.12762040e-02,
         5.78894883e-01, -4.77645569e+00],
       [ 9.65809568e-01,  7.48744042e-03, -4.65044433e+01,
        -2.00792758e+00, -4.63475586e+00]])

In [11]:
import numpy as np
print(np.mean(skeleton_scaled[:,0]))
print(np.std(skeleton_scaled[:,0]))

2.983906501879686e-17
1.0


In [12]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [13]:
# Define the features set.
X = skeleton_df.copy()
X = X.drop("month", axis=1)
X.head()


classification  latitude     longitude  year
0               0  37.39555 -1.214871e+02  1869
1               0  41.01865 -7.837700e+01  1921
2               1  31.08774 -9.184467e+01  1925
3               1  31.40444 -9.570861e+01  1930
4               1  39.80751 -9.486840e+07  1932

In [14]:
# Define the target set.
y = skeleton_df["month"].values
y[:5]


array([11,  1, 10,  9,  1])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [16]:
# Determine the shape of our training and testing sets.
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(2857, 4)
(953, 4)
(2857,)
(953,)


In [17]:
# Splitting into Train and Test sets into an 80/20 split.
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, random_state=78, train_size=0.80)

In [18]:
# Determine the shape of our training and testing sets.
print(X_train2.shape)
print(X_test2.shape)
print(y_train2.shape)
print(y_test2.shape)


(3048, 4)
(762, 4)
(3048,)
(762,)


In [19]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [20]:
# Creating the decision tree classifier instance.
model = tree.DecisionTreeClassifier()
# Fitting the model.
model = model.fit(X_train_scaled, y_train)

In [21]:
# Making predictions using the testing data.
predictions = model.predict(X_test_scaled)

In [22]:
predictions

array([12, 11,  3,  7,  8,  8,  6,  8,  2,  1,  8,  1,  7,  9,  6,  8,  6,
        1,  8,  5,  4,  6,  4,  8,  6,  7,  4,  1, 11,  7,  8,  4,  8,  7,
        1, 10, 11, 12, 11,  9,  8,  4,  9, 10, 10,  3,  2,  5,  7,  9,  9,
        8, 10,  4,  9,  9,  7, 11,  4,  7,  7, 11,  9, 12, 10,  6,  6,  9,
       11, 11, 10,  9, 10,  2, 12,  1, 11, 11,  7,  7,  7,  1,  8,  7, 10,
        9,  5,  7,  1,  6,  6, 11,  9,  6,  7,  7,  9,  1,  9,  5,  8,  1,
       10,  7, 10,  6,  1, 11,  7,  8,  9, 11,  9,  8,  6,  5,  9,  6,  1,
        4,  3, 10,  6,  1,  6,  9,  5, 10,  6,  7,  5,  5,  7,  3,  7, 11,
        9,  1, 11,  9,  4,  9,  1,  5,  7,  3,  6,  2,  9,  8,  5,  7, 10,
        7, 11, 12, 11,  2,  9,  7,  7,  6,  3,  6,  2, 12,  9, 12,  6, 10,
        1,  6,  1,  4,  8,  1,  4, 12,  9,  6,  8, 11, 10,  1, 10,  9,  2,
        2, 12,  4,  8,  6,  7, 11,  7, 11,  8,  3, 11, 11,  1,  8,  4,  6,
       10, 10,  6,  6, 10,  6,  9, 11,  8,  9,  6, 11,  7,  8,  6, 10,  8,
        6,  8, 12,  9, 11

In [23]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm

array([[10,  2,  3,  4,  4,  9,  9,  5,  4,  9,  2,  1],
       [ 4,  4,  4,  1,  2,  3,  2,  7,  4,  4,  5,  1],
       [ 3,  4,  2,  3,  3,  3,  5,  4,  4,  3,  5,  3],
       [ 7,  1,  2,  0,  2, 13,  8,  5,  9,  8,  5,  3],
       [ 8,  1,  5,  9,  6,  4,  9,  8,  4,  4,  6,  4],
       [ 7,  3,  5,  6,  7, 12, 10,  6,  9, 15,  9,  1],
       [ 4,  7,  4,  3,  4, 17, 13, 13, 19, 15,  9,  4],
       [12,  5,  3,  7,  6, 10, 11,  9, 13, 20, 12,  8],
       [ 9,  5,  0,  2,  6,  9, 13, 13, 12,  6, 16, 11],
       [10,  4,  5,  3,  5, 12, 17, 11, 14, 10, 12,  8],
       [ 5,  2,  6,  5,  8,  8, 19, 11,  8, 10,  8,  6],
       [ 2,  3,  1,  3,  6,  3,  5,  7,  5,  7,  6,  2]])

In [25]:
# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1", "Actual 2", "Actual 3", "Actual 4", "Actual 5","Actual 6", "Actual 7", "Actual 8","Actual 9", "Actual 10", "Actual 11"], columns=["Predicted 0", "Predicted 1", "Predicted 2", "Predicted 3", "Predicted 4", "Predicted 5", "Predicted 6", "Predicted 7", "Predicted 8", "Predicted 9", "Predicted 10", "Predicted 11"])

cm_df

Predicted 0  Predicted 1  Predicted 2  Predicted 3  Predicted 4  \
Actual 0            10            2            3            4            4   
Actual 1             4            4            4            1            2   
Actual 2             3            4            2            3            3   
Actual 3             7            1            2            0            2   
Actual 4             8            1            5            9            6   
Actual 5             7            3            5            6            7   
Actual 6             4            7            4            3            4   
Actual 7            12            5            3            7            6   
Actual 8             9            5            0            2            6   
Actual 9            10            4            5            3            5   
Actual 10            5            2            6            5            8   
Actual 11            2            3            1            3            6   

           Predicted 5  Predicted 6  Predicted 7  Predicted 8  Predicted 9  \
Actual 0             9            9            5            4            9   
Actual 1             3            2            7            4            4   
Actual 2             3            5            4            4            3   
Actual 3            13            8            5            9            8   
Actual 4             4            9            8            4            4   
Actual 5            12           10            6            9           15   
Actual 6            17           13           13           19           15   
Actual 7            10           11            9           13           20   
Actual 8             9           13           13           12            6   
Actual 9            12           17           11           14           10   
Actual 10            8           19           11            8           10   
Actual 11            3            5            7            5            7   

           Predicted 10  Predicted 11  
Actual 0              2             1  
Actual 1              5             1  
Actual 2              5             3  
Actual 3              5             3  
Actual 4              6             4  
Actual 5              9             1  
Actual 6              9             4  
Actual 7             12             8  
Actual 8             16            11  
Actual 9             12             8  
Actual 10             8             6  
Actual 11             6             2

In [26]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [27]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1  Predicted 2  Predicted 3  Predicted 4  \
Actual 0            10            2            3            4            4   
Actual 1             4            4            4            1            2   
Actual 2             3            4            2            3            3   
Actual 3             7            1            2            0            2   
Actual 4             8            1            5            9            6   
Actual 5             7            3            5            6            7   
Actual 6             4            7            4            3            4   
Actual 7            12            5            3            7            6   
Actual 8             9            5            0            2            6   
Actual 9            10            4            5            3            5   
Actual 10            5            2            6            5            8   
Actual 11            2            3            1            3            6   

           Predicted 5  Predicted 6  Predicted 7  Predicted 8  Predicted 9  \
Actual 0             9            9            5            4            9   
Actual 1             3            2            7            4            4   
Actual 2             3            5            4            4            3   
Actual 3            13            8            5            9            8   
Actual 4             4            9            8            4            4   
Actual 5            12           10            6            9           15   
Actual 6            17           13           13           19           15   
Actual 7            10           11            9           13           20   
Actual 8             9           13           13           12            6   
Actual 9            12           17           11           14           10   
Actual 10            8           19           11            8           10   
Actual 11            3            5            7            5            7   

           Predicted 10  Predicted 11  
Actual 0              2             1  
Actual 1              5             1  
Actual 2              5             3  
Actual 3              5             3  
Actual 4              6             4  
Actual 5              9             1  
Actual 6              9             4  
Actual 7             12             8  
Actual 8             16            11  
Actual 9             12             8  
Actual 10             8             6  
Actual 11             6             2

Accuracy Score : 0.09233997901364113
Classification Report
              precision    recall  f1-score   support

           1       0.12      0.16      0.14        62
           2       0.10      0.10      0.10        41
           3       0.05      0.05      0.05        42
           4       0.00      0.00      0.00        63
           5       0.10      0.09      0.09        68
           6       0.12      0.13      0.12        90
           7       0.11      0.12      0.11       112
           8       0.09      0.08      0.08       116
           9       0.11      0.12      0.12       102
          10       0.09      0.09      0.09       111
          11       0.08      0.08      0.08        96
          12       0.04      0.04      0.04        50

    accuracy                           0.09       953
   macro avg       0.08      0.09      0.09       953
weighted avg       0.09      0.09      0.09       953



In [28]:
from sklearn.ensemble import RandomForestClassifier


In [45]:
# Define the features set.
X = skeleton_df.copy()
X = X.drop("month", axis=1)
X.head()

classification  latitude     longitude  year
0               0  37.39555 -1.214871e+02  1869
1               0  41.01865 -7.837700e+01  1921
2               1  31.08774 -9.184467e+01  1925
3               1  31.40444 -9.570861e+01  1930
4               1  39.80751 -9.486840e+07  1932

In [46]:
# Define the target set.
y = skeleton_df["month"].values
y[:5]

array([11,  1, 10,  9,  1])

In [47]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [48]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [49]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=500, random_state=78) 

In [50]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [51]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [52]:
predictions

array([ 6,  9, 10, 11,  8,  9,  6, 10, 11, 10,  5,  4, 12,  9,  7, 11,  6,
        1,  4,  5,  4,  6,  4,  8,  9,  7,  9,  9, 11, 10,  4,  7,  8,  7,
        1, 10, 10, 12,  8,  9, 10, 10,  8, 10, 10,  7,  7,  7,  7, 10,  1,
        2,  7,  4,  6, 12,  7, 11,  4,  5,  9, 11,  9, 10, 10,  7,  9, 10,
       11,  8, 10,  9,  3, 10,  6, 11, 11,  7,  7,  7,  7,  2, 11,  5, 10,
        4,  5,  3,  1, 11,  1,  7,  7,  1,  7,  7,  9,  9,  4,  9,  9, 11,
       10, 11, 11,  4,  9, 10,  7, 10, 10,  4,  9,  8,  6,  5, 10,  6,  6,
        8,  7,  2,  8,  7,  2, 10,  5, 10,  8,  7,  3,  5,  7,  3,  9, 10,
        8,  1,  1,  9,  2,  6,  1,  5,  7,  7, 10,  2,  9, 11,  5,  7,  7,
       11, 11, 12,  7,  9,  9,  3,  7,  6,  9,  7,  1, 10,  9, 12,  6,  5,
       11,  9,  1, 10,  7,  1,  9,  6,  3,  6,  7,  9,  9, 10, 10,  8,  7,
        8,  1,  4,  8, 10,  1, 11,  7, 11,  9,  3, 11, 11,  1,  7,  4,  6,
       10, 10,  6,  6,  4,  6,  6, 11,  8,  9,  6,  9, 10,  8,  6, 10,  7,
        8,  7, 12,  9,  8

In [54]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1", "Actual 2", "Actual 3", "Actual 4", "Actual 5","Actual 6", "Actual 7", "Actual 8","Actual 9", "Actual 10", "Actual 11"], columns=["Predicted 0", "Predicted 1", "Predicted 2", "Predicted 3", "Predicted 4", "Predicted 5", "Predicted 6", "Predicted 7", "Predicted 8", "Predicted 9", "Predicted 10", "Predicted 11"])

cm_df

Predicted 0  Predicted 1  Predicted 2  Predicted 3  Predicted 4  \
Actual 0             8            8            2            6            1   
Actual 1             4            4            2            2            2   
Actual 2             1            3            4            2            3   
Actual 3             2            3            1            0            1   
Actual 4             5            1            3           10            5   
Actual 5             4            8            5            5            7   
Actual 6             5            2            2            7            8   
Actual 7             7            3            3            2            7   
Actual 8             6            2            3            4            3   
Actual 9             8            2            4            2            8   
Actual 10            5            2            5            6            5   
Actual 11            1            1            0            2            2   

           Predicted 5  Predicted 6  Predicted 7  Predicted 8  Predicted 9  \
Actual 0             3            9            3            7           12   
Actual 1             2            4            6            4            4   
Actual 2             5           10            3            3            2   
Actual 3             2           13            9            6           14   
Actual 4             4           12            8            5            8   
Actual 5             6           13            7           12           13   
Actual 6            19           16           10           15           16   
Actual 7            10           19           16           10           23   
Actual 8            11           17           17           14            9   
Actual 9             7           18           13           10           26   
Actual 10            5           17            9            9           18   
Actual 11            3            9            3           11           11   

           Predicted 10  Predicted 11  
Actual 0              3             0  
Actual 1              7             0  
Actual 2              4             2  
Actual 3              7             5  
Actual 4              5             2  
Actual 5              8             2  
Actual 6              7             5  
Actual 7             10             6  
Actual 8              9             7  
Actual 9              6             7  
Actual 10            12             3  
Actual 11             5             2

In [55]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [56]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1  Predicted 2  Predicted 3  Predicted 4  \
Actual 0             8            8            2            6            1   
Actual 1             4            4            2            2            2   
Actual 2             1            3            4            2            3   
Actual 3             2            3            1            0            1   
Actual 4             5            1            3           10            5   
Actual 5             4            8            5            5            7   
Actual 6             5            2            2            7            8   
Actual 7             7            3            3            2            7   
Actual 8             6            2            3            4            3   
Actual 9             8            2            4            2            8   
Actual 10            5            2            5            6            5   
Actual 11            1            1            0            2            2   

           Predicted 5  Predicted 6  Predicted 7  Predicted 8  Predicted 9  \
Actual 0             3            9            3            7           12   
Actual 1             2            4            6            4            4   
Actual 2             5           10            3            3            2   
Actual 3             2           13            9            6           14   
Actual 4             4           12            8            5            8   
Actual 5             6           13            7           12           13   
Actual 6            19           16           10           15           16   
Actual 7            10           19           16           10           23   
Actual 8            11           17           17           14            9   
Actual 9             7           18           13           10           26   
Actual 10            5           17            9            9           18   
Actual 11            3            9            3           11           11   

           Predicted 10  Predicted 11  
Actual 0              3             0  
Actual 1              7             0  
Actual 2              4             2  
Actual 3              7             5  
Actual 4              5             2  
Actual 5              8             2  
Actual 6              7             5  
Actual 7             10             6  
Actual 8              9             7  
Actual 9              6             7  
Actual 10            12             3  
Actual 11             5             2

Accuracy Score : 0.11857292759706191
Classification Report
              precision    recall  f1-score   support

           1       0.14      0.13      0.14        62
           2       0.10      0.10      0.10        41
           3       0.12      0.10      0.11        42
           4       0.00      0.00      0.00        63
           5       0.10      0.07      0.08        68
           6       0.08      0.07      0.07        90
           7       0.10      0.14      0.12       112
           8       0.15      0.14      0.15       116
           9       0.13      0.14      0.13       102
          10       0.17      0.23      0.19       111
          11       0.14      0.12      0.13        96
          12       0.05      0.04      0.04        50

    accuracy                           0.12       953
   macro avg       0.11      0.11      0.11       953
weighted avg       0.11      0.12      0.12       953



In [57]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances


array([0.05791302, 0.407109  , 0.2947764 , 0.24020157])

In [58]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.4071090041331605, 'latitude'),
 (0.2947764033459284, 'longitude'),
 (0.24020157203197479, 'year'),
 (0.057913020488936325, 'classification')]

In [59]:
import joblib


In [62]:
# save
joblib.dump(RandomForestClassifier, "./random_forest2.joblib")


['./random_forest2.joblib']

In [63]:
# load, no need to initialize the loaded_rf
loaded_rf = joblib.load("./random_forest2.joblib")