In [1]:
import pandas as pd
import plotly.express as px
#import hvplot.pandas
from sklearn.cluster import KMeans

In [2]:
# Loading data
file_path = "../sources/datafiniti-restaurants-burritos-and-tacos/data/just_tacos_and_burritos.csv"
all_tacos = pd.read_csv(file_path)
all_tacos.head(10)

id                   address  \
0  AVwc__cikufWRAb51QjV         610 Commercial St   
1  AVwc__cikufWRAb51QjV         610 Commercial St   
2  AVwc__dF_7pvs4fz1Ncy      9521 Morton Davis Dr   
3  AVwc__kCByjofQCxkdm-  10550 W I 25 Frontage Rd   
4  AVwc__WtByjofQCxkdkR             8495 W 3rd St   
5  AVwc__WtByjofQCxkdkR             8495 W 3rd St   
6  AVwc__WtByjofQCxkdkR             8495 W 3rd St   
7  AVwc__WtByjofQCxkdkR             8495 W 3rd St   
8  AVwc__WtByjofQCxkdkR             8495 W 3rd St   
9  AVwc__WtByjofQCxkdkR             8495 W 3rd St   

                                          categories         city country  \
0  Restaurant Delivery Service,Restaurants,Pizza,...     Atchison      US   
1  Restaurant Delivery Service,Restaurants,Pizza,...     Atchison      US   
2       Golf Course, American Restaurant, and Resort    Patterson      US   
3                               Fast Food Restaurant     Longmont      US   
4  Mexican Restaurant Mid-City West,Mexican Resta...  Los Angeles      US   
5  Mexican Restaurant Mid-City West,Mexican Resta...  Los Angeles      US   
6  Mexican Restaurant Mid-City West,Mexican Resta...  Los Angeles      US   
7  Mexican Restaurant Mid-City West,Mexican Resta...  Los Angeles      US   
8  Mexican Restaurant Mid-City West,Mexican Resta...  Los Angeles      US   
9  Mexican Restaurant Mid-City West,Mexican Resta...  Los Angeles      US   

                      cuisines             dateadded           dateupdated  \
0  Restaurant Delivery Service  2016-03-02T11:49:34Z  2017-02-01T18:04:44Z   
1  Restaurant Delivery Service  2016-03-02T11:49:34Z  2017-02-01T18:04:44Z   
2                          NaN  2016-10-14T01:58:25Z  2016-10-14T01:58:25Z   
3                          NaN  2016-09-09T17:30:34Z  2016-10-04T05:15:17Z   
4                      Mexican  2016-05-19T11:50:25Z  2016-09-11T00:06:37Z   
5                      Mexican  2016-05-19T11:50:25Z  2016-09-11T00:06:37Z   
6                      Mexican  2016-05-19T11:50:25Z  2016-09-11T00:06:37Z   
7                      Mexican  2016-05-19T11:50:25Z  2016-09-11T00:06:37Z   
8                      Mexican  2016-05-19T11:50:25Z  2016-09-11T00:06:37Z   
9                      Mexican  2016-05-19T11:50:25Z  2016-09-11T00:06:37Z   

                                                keys   latitude  ...  \
0          us/ks/atchison/610commercialst/-138126000  39.561570  ...   
1          us/ks/atchison/610commercialst/-138126000  39.561570  ...   
2  us/grayson/patterson/9521mortondavisdr/-522005016  37.401855  ...   
3  us/niwot/longmont/10550wi25frontagerd/-1161002137        NaN  ...   
4   us/bicentennial/losangeles/8495w3rdst/-251199537  34.080724  ...   
5   us/bicentennial/losangeles/8495w3rdst/-251199537  34.080724  ...   
6   us/bicentennial/losangeles/8495w3rdst/-251199537  34.080724  ...   
7   us/bicentennial/losangeles/8495w3rdst/-251199537  34.080724  ...   
8   us/bicentennial/losangeles/8495w3rdst/-251199537  34.080724  ...   
9   us/bicentennial/losangeles/8495w3rdst/-251199537  34.080724  ...   

                                   menus_description  \
0                                                NaN   
1  Beef, onion, cheddar cheese, lettuce,  refried...   
2  Beef barbacoa or chicken, spanish rice, pico d...   
3                                                NaN   
4  Wahoo, avocado, cabbage, pico de gallo  and av...   
5  Hand breaded fried wahoo, topped with   cabbag...   
6  Any combination of two original baja or americ...   
7  Grilled corn tortillas with salsa, onions and ...   
8                                                NaN   
9                        Cabo style or caesar style.   

                      menus_name                               name  \
0                           Taco                    Gambino's Pizza   
1                           Taco                    Gambino's Pizza   
2               Smotherd Burrito  Diablo Grande Golf & Country Club   
3                Sausage Burrito    

In [3]:
all_tacos.columns.tolist()

['id',
 'address',
 'categories',
 'city',
 'country',
 'cuisines',
 'dateadded',
 'dateupdated',
 'keys',
 'latitude',
 'longitude',
 'menupageurl',
 'menus_amountmax',
 'menus_amountmin',
 'menus_category',
 'menus_currency',
 'menus_dateseen',
 'menus_description',
 'menus_name',
 'name',
 'postalcode',
 'pricerangecurrency',
 'pricerangemin',
 'pricerangemax',
 'province',
 'websites',
 'location']

In [59]:
all_tacos = all_tacos.drop(['id', 'address', 'categories','city', 'country','dateadded','dateupdated','keys', 'menupageurl','menus_amountmax',
 'menus_amountmin','menus_currency','menus_dateseen', 'menus_name','postalcode','pricerangecurrency','pricerangemin','pricerangemax','province','websites',], axis=1)
all_tacos.head()

classification  latitude     longitude  month  year
0        Class A  37.39555 -1.214871e+02     11  1869
1        Class A  41.01865 -7.837700e+01      1  1921
2        Class B  31.08774 -9.184467e+01     10  1925
3        Class B  31.40444 -9.570861e+01      9  1930
4        Class B  39.80751 -9.486840e+07      1  1932

In [60]:
skeleton_df.drop(skeleton_df[skeleton_df['classification'] != "Class A"].index, inplace = True)
skeleton_df.head()

classification  latitude  longitude  month  year
0        Class A  37.39555  -121.4871     11  1869
1        Class A  41.01865   -78.3770      1  1921
5        Class A  49.17500  -121.5250      3  1934
6        Class A  38.01000   -87.3203      8  1937
8        Class A  46.24639  -120.8681     10  1941

In [61]:
skeleton_df.classification.unique()

array(['Class A'], dtype=object)

In [62]:
skeleton_df = skeleton_df.drop(['classification'], axis=1)
skeleton_df.head()

latitude  longitude  month  year
0  37.39555  -121.4871     11  1869
1  41.01865   -78.3770      1  1921
5  49.17500  -121.5250      3  1934
6  38.01000   -87.3203      8  1937
8  46.24639  -120.8681     10  1941

In [63]:
#List the data types
skeleton_df.dtypes

latitude     float64
longitude    float64
month          int64
year           int64
dtype: object

In [64]:
skeleton_df = skeleton_df.drop(['year'], axis=1)
skeleton_df.head()

latitude  longitude  month
0  37.39555  -121.4871     11
1  41.01865   -78.3770      1
5  49.17500  -121.5250      3
6  38.01000   -87.3203      8
8  46.24639  -120.8681     10

In [65]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()

In [66]:
# Generate our categorical variable list
skeleton_scaled = data_scaler.fit_transform(skeleton_df)

In [67]:
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()


In [68]:
skeleton_scaled[:5]

array([[-0.30628302,  0.03254059,  1.20961823],
       [ 0.29981088,  0.03287043, -2.01115815],
       [ 1.66425401,  0.0325403 , -1.36700287],
       [-0.20349414,  0.032802  ,  0.24338532],
       [ 1.17433857,  0.03254533,  0.8875406 ]])

In [69]:
import numpy as np
print(np.mean(skeleton_scaled[:,0]))
print(np.std(skeleton_scaled[:,0]))

-1.4248350374081165e-16
1.0


In [70]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [23]:
# Define the features set.
X = skeleton_df.copy()
X = X.drop("month", axis=1)
X.head()


latitude  longitude
0  37.39555  -121.4871
1  41.01865   -78.3770
5  49.17500  -121.5250
6  38.01000   -87.3203
8  46.24639  -120.8681

In [24]:
# Define the target set.
y = skeleton_df["month"].values
y[:5]


array([11,  1,  3,  8, 10])

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [26]:
# Determine the shape of our training and testing sets.
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1421, 2)
(474, 2)
(1421,)
(474,)


In [27]:
# Splitting into Train and Test sets into an 80/20 split.
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, random_state=78, train_size=0.80)

In [28]:
# Determine the shape of our training and testing sets.
print(X_train2.shape)
print(X_test2.shape)
print(y_train2.shape)
print(y_test2.shape)


(1516, 2)
(379, 2)
(1516,)
(379,)


In [29]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [30]:
# Creating the decision tree classifier instance.
model = tree.DecisionTreeClassifier()
# Fitting the model.
model = model.fit(X_train_scaled, y_train)

In [31]:
# Making predictions using the testing data.
predictions = model.predict(X_test_scaled)

In [32]:
predictions

array([ 2,  7,  1,  1,  7,  7, 10, 10,  1,  5,  1, 11,  7,  2, 11,  7,  8,
        7, 11,  4,  7,  3, 10,  4,  7, 10,  3,  8, 11,  7, 10,  9, 10,  7,
        4,  1, 12,  9,  1, 11,  8,  2,  7,  8,  2, 12,  2,  4,  8,  2, 11,
        9,  4,  4,  6,  3,  8,  7,  7,  8, 10,  4,  7, 11,  4,  7,  1,  5,
       12, 10,  4, 11,  8,  4,  9, 12,  8,  1,  8,  9,  1,  5,  3, 10,  9,
        7, 12,  8,  9,  9,  6,  7,  8,  9, 10,  9,  6, 10,  7,  7,  7,  9,
       11,  6, 10,  6,  4, 11, 12,  7,  7,  7,  1,  3,  7,  4,  9,  2,  1,
       11,  7, 11,  9, 11,  7, 12,  9,  7,  1,  8,  6, 10,  7,  3,  3, 10,
        6, 11,  7, 11, 10, 10,  7,  1,  7, 11,  5,  1,  7,  6, 11,  6,  7,
        5,  7, 10,  7,  2,  7,  8,  4,  6,  9,  6,  7,  2,  7,  8,  4, 11,
        4,  1,  3,  7,  6,  8,  6,  9,  6,  9, 12,  7,  7,  7,  7, 10,  5,
        9,  2,  2,  7, 10,  7,  3,  8,  4,  2,  1,  9,  7,  9,  2, 10,  9,
       10,  9,  7, 10,  1, 11,  8,  8, 10,  6,  7, 11,  1,  7,  9,  7,  1,
        2,  7, 10,  1,  7

In [33]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm

array([[ 2,  1,  0,  4,  2,  3,  7,  0,  3,  4,  0,  0],
       [ 2,  1,  0,  1,  0,  0,  4,  3,  2,  2,  1,  1],
       [ 1,  0,  3,  1,  0,  2,  3,  3,  1,  3,  5,  1],
       [ 0,  1,  1,  3,  2,  3,  6,  1,  3,  1,  4,  0],
       [ 3,  2,  2,  0,  3,  1,  8,  1,  6,  7,  0,  4],
       [ 1,  5,  1,  4,  2,  4, 12,  3,  4,  7,  5,  1],
       [ 3,  1,  3,  5,  2,  2, 16,  0,  4,  8,  8,  4],
       [ 6,  2,  4,  4,  1,  5, 11,  7,  8, 14,  2,  2],
       [ 9,  1,  4,  4,  3,  1,  7,  5,  4,  5,  6,  3],
       [ 9,  2,  2,  5,  2,  3,  6,  6,  3,  4,  3,  4],
       [ 2,  1,  3,  1,  3,  5,  7,  4,  7, 10,  6,  2],
       [ 3,  0,  0,  4,  0,  0,  0,  1,  5,  4,  4,  2]])

In [35]:
# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1", "Actual 2", "Actual 3", "Actual 4", "Actual 5","Actual 6", "Actual 7", "Actual 8","Actual 9", "Actual 10", "Actual 11"], columns=["Predicted 0", "Predicted 1", "Predicted 2", "Predicted 3", "Predicted 4", "Predicted 5", "Predicted 6", "Predicted 7", "Predicted 8", "Predicted 9", "Predicted 10", "Predicted 11"])

cm_df

Predicted 0  Predicted 1  Predicted 2  Predicted 3  Predicted 4  \
Actual 0             2            1            0            4            2   
Actual 1             2            1            0            1            0   
Actual 2             1            0            3            1            0   
Actual 3             0            1            1            3            2   
Actual 4             3            2            2            0            3   
Actual 5             1            5            1            4            2   
Actual 6             3            1            3            5            2   
Actual 7             6            2            4            4            1   
Actual 8             9            1            4            4            3   
Actual 9             9            2            2            5            2   
Actual 10            2            1            3            1            3   
Actual 11            3            0            0            4            0   

           Predicted 5  Predicted 6  Predicted 7  Predicted 8  Predicted 9  \
Actual 0             3            7            0            3            4   
Actual 1             0            4            3            2            2   
Actual 2             2            3            3            1            3   
Actual 3             3            6            1            3            1   
Actual 4             1            8            1            6            7   
Actual 5             4           12            3            4            7   
Actual 6             2           16            0            4            8   
Actual 7             5           11            7            8           14   
Actual 8             1            7            5            4            5   
Actual 9             3            6            6            3            4   
Actual 10            5            7            4            7           10   
Actual 11            0            0            1            5            4   

           Predicted 10  Predicted 11  
Actual 0              0             0  
Actual 1              1             1  
Actual 2              5             1  
Actual 3              4             0  
Actual 4              0             4  
Actual 5              5             1  
Actual 6              8             4  
Actual 7              2             2  
Actual 8              6             3  
Actual 9              3             4  
Actual 10             6             2  
Actual 11             4             2

In [36]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [37]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1  Predicted 2  Predicted 3  Predicted 4  \
Actual 0             2            1            0            4            2   
Actual 1             2            1            0            1            0   
Actual 2             1            0            3            1            0   
Actual 3             0            1            1            3            2   
Actual 4             3            2            2            0            3   
Actual 5             1            5            1            4            2   
Actual 6             3            1            3            5            2   
Actual 7             6            2            4            4            1   
Actual 8             9            1            4            4            3   
Actual 9             9            2            2            5            2   
Actual 10            2            1            3            1            3   
Actual 11            3            0            0            4            0   

           Predicted 5  Predicted 6  Predicted 7  Predicted 8  Predicted 9  \
Actual 0             3            7            0            3            4   
Actual 1             0            4            3            2            2   
Actual 2             2            3            3            1            3   
Actual 3             3            6            1            3            1   
Actual 4             1            8            1            6            7   
Actual 5             4           12            3            4            7   
Actual 6             2           16            0            4            8   
Actual 7             5           11            7            8           14   
Actual 8             1            7            5            4            5   
Actual 9             3            6            6            3            4   
Actual 10            5            7            4            7           10   
Actual 11            0            0            1            5            4   

           Predicted 10  Predicted 11  
Actual 0              0             0  
Actual 1              1             1  
Actual 2              5             1  
Actual 3              4             0  
Actual 4              0             4  
Actual 5              5             1  
Actual 6              8             4  
Actual 7              2             2  
Actual 8              6             3  
Actual 9              3             4  
Actual 10             6             2  
Actual 11             4             2

Accuracy Score : 0.1160337552742616
Classification Report
              precision    recall  f1-score   support

           1       0.05      0.08      0.06        26
           2       0.06      0.06      0.06        17
           3       0.13      0.13      0.13        23
           4       0.08      0.12      0.10        25
           5       0.15      0.08      0.11        37
           6       0.14      0.08      0.10        49
           7       0.18      0.29      0.22        56
           8       0.21      0.11      0.14        66
           9       0.08      0.08      0.08        52
          10       0.06      0.08      0.07        49
          11       0.14      0.12      0.13        51
          12       0.08      0.09      0.09        23

    accuracy                           0.12       474
   macro avg       0.11      0.11      0.11       474
weighted avg       0.13      0.12      0.11       474



In [38]:
from sklearn.ensemble import RandomForestClassifier


In [40]:
# Define the features set.
X = skeleton_df.copy()
X = X.drop("month", axis=1)
X.head()

latitude  longitude
0  37.39555  -121.4871
1  41.01865   -78.3770
5  49.17500  -121.5250
6  38.01000   -87.3203
8  46.24639  -120.8681

In [41]:
# Define the target set.
y = skeleton_df["month"].values
y[:5]

array([11,  1,  3,  8, 10])

In [42]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [43]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [44]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=500, random_state=78) 

In [45]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [46]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [47]:
predictions

array([12,  7,  7,  1,  7,  7,  9, 10,  4,  5, 11, 11,  7, 11, 11,  7,  6,
        7, 11,  4,  7,  6,  9,  2,  7, 11, 12, 11, 11,  7, 10, 10, 10,  7,
        4,  8,  3,  9, 11,  5,  8, 10,  7,  8,  2, 12,  2,  5,  8,  2, 11,
        9,  1,  4,  6,  3,  8, 10,  7,  7, 10, 10,  7, 11,  8,  9,  1,  5,
        4,  1,  4, 11,  9,  4,  6,  7,  9,  1,  8,  9,  1,  5,  3, 10, 12,
        7,  7, 11,  9,  9,  6,  7,  8, 10,  9,  7,  7, 10,  7,  7, 12,  9,
       11,  6, 10,  4,  4, 11, 12, 11, 11,  7,  9, 10,  6,  4, 12,  2, 10,
       11,  7, 11,  8, 11, 10, 12,  9, 12,  6, 11, 11, 11,  7,  3,  9,  8,
        6, 11,  7, 11,  5, 10,  7,  4,  7,  1,  5, 12,  7,  6, 11, 10,  4,
        5,  3, 10,  5,  2,  7,  8, 10,  6, 10,  5,  7, 11,  7, 11,  1, 11,
        7,  1,  3,  7,  6,  8,  6, 11,  6,  8, 12, 10,  7,  7,  7, 10, 10,
        9,  6,  2,  7, 11,  9,  3,  9, 12,  2,  1,  9,  8,  9,  8,  7,  9,
       10,  8,  7, 10, 10, 11,  3,  8, 10, 11, 12, 11,  1,  4,  9,  4, 11,
        2,  6, 10,  5,  7

In [49]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1", "Actual 2", "Actual 3", "Actual 4", "Actual 5","Actual 6", "Actual 7", "Actual 8","Actual 9", "Actual 10", "Actual 11"], columns=["Predicted 0", "Predicted 1", "Predicted 2", "Predicted 3", "Predicted 4", "Predicted 5", "Predicted 6", "Predicted 7", "Predicted 8", "Predicted 9", "Predicted 10", "Predicted 11"])

cm_df

Predicted 0  Predicted 1  Predicted 2  Predicted 3  Predicted 4  \
Actual 0             0            3            2            1            1   
Actual 1             1            1            0            2            0   
Actual 2             1            0            3            1            0   
Actual 3             0            0            0            4            4   
Actual 4             0            3            0            3            3   
Actual 5             2            3            1            1            6   
Actual 6             0            1            3            3            2   
Actual 7             2            2            1            3            2   
Actual 8             5            1            5            2            2   
Actual 9             5            1            2            7            3   
Actual 10            3            0            0            3            4   
Actual 11            5            1            1            2            3   

           Predicted 5  Predicted 6  Predicted 7  Predicted 8  Predicted 9  \
Actual 0             3            3            1            2            6   
Actual 1             0            3            1            1            3   
Actual 2             2            3            2            3            3   
Actual 3             3            5            1            3            2   
Actual 4             1            6            5            7            4   
Actual 5             3            8            6            5            6   
Actual 6             3           13            2            7           10   
Actual 7             7           11            5            9           14   
Actual 8             3            5            7            9            3   
Actual 9             4            7            4            2           11   
Actual 10            5            7            5            5           10   
Actual 11            0            1            0            2            3   

           Predicted 10  Predicted 11  
Actual 0              3             1  
Actual 1              2             3  
Actual 2              5             0  
Actual 3              3             0  
Actual 4              3             2  
Actual 5              4             4  
Actual 6              8             4  
Actual 7              6             4  
Actual 8              7             3  
Actual 9              2             1  
Actual 10             9             0  
Actual 11             4             1

In [50]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [51]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1  Predicted 2  Predicted 3  Predicted 4  \
Actual 0             0            3            2            1            1   
Actual 1             1            1            0            2            0   
Actual 2             1            0            3            1            0   
Actual 3             0            0            0            4            4   
Actual 4             0            3            0            3            3   
Actual 5             2            3            1            1            6   
Actual 6             0            1            3            3            2   
Actual 7             2            2            1            3            2   
Actual 8             5            1            5            2            2   
Actual 9             5            1            2            7            3   
Actual 10            3            0            0            3            4   
Actual 11            5            1            1            2            3   

           Predicted 5  Predicted 6  Predicted 7  Predicted 8  Predicted 9  \
Actual 0             3            3            1            2            6   
Actual 1             0            3            1            1            3   
Actual 2             2            3            2            3            3   
Actual 3             3            5            1            3            2   
Actual 4             1            6            5            7            4   
Actual 5             3            8            6            5            6   
Actual 6             3           13            2            7           10   
Actual 7             7           11            5            9           14   
Actual 8             3            5            7            9            3   
Actual 9             4            7            4            2           11   
Actual 10            5            7            5            5           10   
Actual 11            0            1            0            2            3   

           Predicted 10  Predicted 11  
Actual 0              3             1  
Actual 1              2             3  
Actual 2              5             0  
Actual 3              3             0  
Actual 4              3             2  
Actual 5              4             4  
Actual 6              8             4  
Actual 7              6             4  
Actual 8              7             3  
Actual 9              2             1  
Actual 10             9             0  
Actual 11             4             1

Accuracy Score : 0.1308016877637131
Classification Report
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        26
           2       0.06      0.06      0.06        17
           3       0.17      0.13      0.15        23
           4       0.12      0.16      0.14        25
           5       0.10      0.08      0.09        37
           6       0.09      0.06      0.07        49
           7       0.18      0.23      0.20        56
           8       0.13      0.08      0.10        66
           9       0.16      0.17      0.17        52
          10       0.15      0.22      0.18        49
          11       0.16      0.18      0.17        51
          12       0.04      0.04      0.04        23

    accuracy                           0.13       474
   macro avg       0.11      0.12      0.11       474
weighted avg       0.13      0.13      0.13       474



In [52]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances


array([0.52404891, 0.47595109])

In [53]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.5240489116102415, 'latitude'), (0.47595108838975864, 'longitude')]

In [54]:
import joblib


In [55]:
# save
joblib.dump(RandomForestClassifier, "./random_forest3.joblib")


['./random_forest3.joblib']

In [46]:
# load, no need to initialize the loaded_rf
loaded_rf = joblib.load("./random_forest3.joblib")